# Generated by Django 4.2.1 on 2025-09-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram chat ID для уведомлений",
                max_length=50,
                null=True,
            ),
        ),
    ]
