# Generated by Django 4.2.1 on 2025-09-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_rename_owner_site_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("fail", "Fail"),
                            ("degraded", "Degraded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="sites.site",
                    ),
                ),
            ],
        ),
    ]
