# Generated by Django 4.2.1 on 2025-09-20 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkresult",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="checkresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checkresult",
            name="error_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
