# Generated by Django 4.2.1 on 2025-09-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="owner",
            new_name="user",
        ),
    ]
