# Generated by Django 4.2.1 on 2025-09-20 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0003_rename_url_to_target"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="user",
        ),
        migrations.AddField(
            model_name="site",
            name="check_type",
            field=models.CharField(
                choices=[("http", "HTTP/HTTPS"), ("ping", "Ping"), ("tcp", "TCP Port")],
                default="http",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="degraded_latency_ms",
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name="site",
            name="domain_check_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="site",
            name="domain_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="domain_expiry_alert_days",
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name="site",
            name="domain_last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="fail_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="site",
            name="fail_threshold",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="site",
            name="host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="site",
            name="http_method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("HEAD", "HEAD"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                ],
                default="GET",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="recovery_threshold",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="site",
            name="ssl_check_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="site",
            name="ssl_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="ssl_expiry_alert_days",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="site",
            name="ssl_last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="success_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="site",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="sites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("fail", "Fail"),
                    ("degraded", "Degraded"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="target",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["active", "status"], name="sites_site_active_55211b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["updated_at"], name="sites_site_updated_6d558a_idx"
            ),
        ),
    ]
