# Generated by Django 4.2.1 on 2025-09-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_remove_site_user_site_check_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="timeout",
            field=models.IntegerField(
                choices=[
                    (1, "1 секунда"),
                    (10, "10 секунд"),
                    (30, "30 секунд"),
                    (60, "60 секунд"),
                ],
                default=10,
            ),
        ),
    ]
