# Generated by Django 4.2.1 on 2025-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0005_alter_site_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
