# Generated by Django 4.2.1 on 2025-09-21 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_site_last_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="last_notified_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 9, 21, 11, 27, 35, 291480, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
