# Generated by Django 4.2.1 on 2025-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0007_alter_site_last_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
